In [1]:
import pandas as pd
import numpy as np

In [16]:
df = pd.read_excel(r"C:\Users\sruti\Desktop\E-Commerce Sales Analysis\DATA SETS\Cleaned_Superstore_data.xlsx")
df.head()

,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,State,Postal_Code,Region,Product_ID,Category,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit
0,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [17]:
df.shape

(9994, 20)

In [3]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

Total Sales

In [13]:
Total_Sales_Amount =df["Sales"].sum()
print(f"Total Sales Amount: ₹{Total_Sales_Amount:,.2f}")

Total Sales Amount: ₹2,297,200.86

Total Profit

In [11]:
df["Profit"].sum()

np.float64(286397.0217)

Total Orders

In [15]:
Total_order = df["Order_ID"].nunique()
print("Total Order Count:", Total_order)

Total Order Count: 5009

Total Average Sales

In [19]:
df["Sales"].mean()

np.float64(229.85800083049827)

Category has the highest Profit

In [20]:
df.groupby("Category")["Profit"].sum().sort_values(ascending=False)

Category
Technology         145454.9481
Office Supplies    122490.8008
Furniture           18451.2728
Name: Profit, dtype: float64

Sub-Category has the Highest Sales

In [21]:
df.groupby("Sub-Category")["Sales"].sum().sort_values(ascending=False)

Sub-Category
Phones         330007.0540
Chairs         328449.1030
Storage        223843.6080
Tables         206965.5320
Binders        203412.7330
Machines       189238.6310
Accessories    167380.3180
Copiers        149528.0300
Bookcases      114879.9963
Appliances     107532.1610
Furnishings     91705.1640
Paper           78479.2060
Supplies        46673.5380
Art             27118.7920
Envelopes       16476.4020
Labels          12486.3120
Fasteners        3024.2800
Name: Sales, dtype: float64

Top 10 Selling Products

In [22]:
df.groupby("Product_Name")["Sales"].sum().sort_values(ascending=False).head(10)

Product_Name
Canon imageCLASS 2200 Advanced Copier                                          61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
HON 5400 Series Task Chairs for Big and Tall                                   21870.576
GBC DocuBind TL300 Electric Binding System                                     19823.479
GBC Ibimaster 500 Manual ProClick Binding System                               19024.500
Hewlett Packard LaserJet 3310 Copier                                           18839.686
HP Designjet T520 Inkjet Large Format Printer - 24" Color                      18374.895
GBC DocuBind P400 Electric Binding System                                      17965.068
High Speed Automatic Electric Letter Opener                                    17030.312
Name: Sales, dtype: float64

TOP 10 Profitable Products

In [23]:
df.groupby("Product_Name")["Profit"].sum().sort_values(ascending=False).head(10)

Product_Name
Canon imageCLASS 2200 Advanced Copier                                          25199.9280
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind     7753.0390
Hewlett Packard LaserJet 3310 Copier                                            6983.8836
Canon PC1060 Personal Laser Copier                                              4570.9347
HP Designjet T520 Inkjet Large Format Printer - 24" Color                       4094.9766
Ativa V4110MDD Micro-Cut Shredder                                               3772.9461
3D Systems Cube Printer, 2nd Generation, Magenta                                3717.9714
Plantronics Savi W720 Multi-Device Wireless Headset System                      3696.2820
Ibico EPK-21 Electric Binding System                                            3345.2823
Zebra ZM400 Thermal Label Printer                                               3343.5360
Name: Profit, dtype: float64

TOP 10 Customers

In [24]:
df.groupby("Customer_Name")["Sales"].sum().sort_values(ascending=False).head(10)

Customer_Name
Sean Miller           25043.050
Tamara Chand          19052.218
Raymond Buch          15117.339
Tom Ashbrook          14595.620
Adrian Barton         14473.571
Ken Lonsdale          14175.229
Sanjit Chand          14142.334
Hunter Lopez          12873.298
Sanjit Engle          12209.438
Christopher Conant    12129.072
Name: Sales, dtype: float64

Region wise Highest Sales

In [25]:
df.groupby("Region")["Sales"].sum().sort_values(ascending=False)

Region
West       725457.8245
East       678781.2400
Central    501239.8908
South      391721.9050
Name: Sales, dtype: float64

State Wise Highest Sales

In [26]:
df.groupby("State")["Sales"].sum().sort_values(ascending=False).head(10)

State
California      457687.6315
New York        310876.2710
Texas           170188.0458
Washington      138641.2700
Pennsylvania    116511.9140
Florida          89473.7080
Illinois         80166.1010
Ohio             78258.1360
Michigan         76269.6140
Virginia         70636.7200
Name: Sales, dtype: float64

City wise Highest Sales

In [27]:
df.groupby("City")["Sales"].sum().sort_values(ascending=False).head(10)

City
New York City    256368.1610
Los Angeles      175851.3410
Seattle          119540.7420
San Francisco    112669.0920
Philadelphia     109077.0130
Houston           64504.7604
Chicago           48539.5410
San Diego         47521.0290
Jacksonville      44713.1830
Springfield       43054.3420
Name: Sales, dtype: float64

Highest revenue Generating Customer segment

In [28]:
df.groupby("Segment")["Sales"].sum().sort_values(ascending=False)

Segment
Consumer       1.161401e+06
Corporate      7.061464e+05
Home Office    4.296531e+05
Name: Sales, dtype: float64

Most Frequently used Shipping Mode

In [29]:
df["Ship_Mode"].value_counts()

Ship_Mode
Standard Class    5968
Second Class      1945
First Class       1538
Same Day           543
Name: count, dtype: int64

Shipping Mode Generates the Highest Sales

In [30]:
df.groupby("Ship_Mode")["Sales"].sum().sort_values(ascending=False)

Ship_Mode
Standard Class    1.358216e+06
Second Class      4.591936e+05
First Class       3.514284e+05
Same Day          1.283631e+05
Name: Sales, dtype: float64

Displays Monthly Sales Ranking

In [31]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [32]:
df.groupby(df["Order_Date"].dt.month_name())["Sales"].sum().sort_values(ascending=False)

Order_Date
November     352461.0710
December     325293.5035
September    307649.9457
March        205005.4888
October      200322.9847
August       159044.0630
May          155028.8117
June         152718.6793
July         147238.0970
April        137762.1286
January       94924.8356
February      59751.2514
Name: Sales, dtype: float64

Relationship Between Sales & Profit

In [33]:
df[["Sales", "Profit"]].corr()

           Sales    Profit
Sales   1.000000  0.479064
Profit  0.479064  1.000000

Lists Products With Negative Profit

In [34]:
df[df["Profit"] < 0][["Product_Name","Profit"]].sort_values(by="Profit")

                                    Product_Name     Profit
7772   Cubify CubeX 3D Printer Double Head Print -6599.9780
683    Cubify CubeX 3D Printer Triple Head Print -3839.9904
9774   GBC DocuBind P400 Electric Binding System -3701.8928
3011   Lexmark MX611dhe Monochrome Laser Printer -3399.9800
4991        Ibico EPK-21 Electric Binding System -2929.4845
...                                          ...        ...
4660        SanDisk Cruzer 16 GB USB Flash Drive    -0.3444
7413   Tensor Brushed Steel Torchiere Floor Lamp    -0.3398
1566  Kingston Digital DataTraveler 16GB USB 2.0    -0.2685
1496    Acco Perma 3000 Stacking Storage Drawers    -0.2098
3228  Kingston Digital DataTraveler 16GB USB 2.0    -0.0895

[1871 rows x 2 columns]

OUTLIERS

Detect Outliers in Multiple Columns

In [35]:
columns = ["Sales", "Profit", "Quantity", "Discount"]

for col in columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    count = df[(df[col] < lower) | (df[col] > upper)].shape[0]

    print(f"{col}: {count} outliers")

Sales: 1167 outliers
Profit: 1881 outliers
Quantity: 170 outliers
Discount: 856 outliers

Correlation

Select Numeric Columns

In [36]:
numeric_df = df.select_dtypes(include=["int64","float64"])

Calculate Correlation Matrix

In [37]:
correlation_matrix = numeric_df.corr()
correlation_matrix

             Postal_Code     Sales  Quantity  Discount    Profit
Postal_Code     1.000000 -0.023854  0.012761  0.058443 -0.029961
Sales          -0.023854  1.000000  0.200795 -0.028190  0.479064
Quantity        0.012761  0.200795  1.000000  0.008623  0.066253
Discount        0.058443 -0.028190  0.008623  1.000000 -0.219487
Profit         -0.029961  0.479064  0.066253 -0.219487  1.000000

Correlation Between sales and Profit

In [39]:
df["Sales"].corr(df["Profit"])

np.float64(0.47906434973770606)

Correlation Between Discount and Profit

In [40]:
df["Discount"].corr(df["Profit"])

np.float64(-0.2194874563717678)

Correlation Between Quantity and Sales

In [41]:
df["Quantity"].corr(df["Profit"])

np.float64(0.06625318912428485)

Correlation Between Quantity and Profit

In [42]:
df["Quantity"].corr(df["Profit"])

np.float64(0.06625318912428485)

Strongest Correlation

In [43]:
correlation_matrix.unstack().sort_values(ascending=False)

Postal_Code  Postal_Code    1.000000
Sales        Sales          1.000000
Profit       Profit         1.000000
Discount     Discount       1.000000
Quantity     Quantity       1.000000
Sales        Profit         0.479064
Profit       Sales          0.479064
Quantity     Sales          0.200795
Sales        Quantity       0.200795
Profit       Quantity       0.066253
Quantity     Profit         0.066253
Discount     Postal_Code    0.058443
Postal_Code  Discount       0.058443
             Quantity       0.012761
Quantity     Postal_Code    0.012761
Discount     Quantity       0.008623
Quantity     Discount       0.008623
Postal_Code  Sales         -0.023854
Sales        Postal_Code   -0.023854
Discount     Sales         -0.028190
Sales        Discount      -0.028190
Postal_Code  Profit        -0.029961
Profit       Postal_Code   -0.029961
Discount     Profit        -0.219487
Profit       Discount      -0.219487
dtype: float64